Avatars: Adds definition of multiple sizes
NiceDash/Vibe pull request #28
Opened 2019-10-30 14:52 UTC by cstuder

Available sizes: small, medium, big

Pixel sizes chosen at random. Initials should always fit (Tested it with `MM`.)

2019-11-02 21:02 UTC, julians300 requested changes

2019-11-02 21:02 UTC, julians300 commented on src/vibe/scss/components/avatars.scss
> +	&.avatar-big {
I would recommend using `large` instead of `big`. This will align more with how bootstrap names their sizes.

2019-11-02 21:02 UTC, julians300 commented on src/views/elements/Avatars.js
> +          <Avatar initials="JS" color="primary" size="big" /> <Avatar initials="TD" color="secondary" size="big" />{' '}
same here, I would consider using `large`

2019-11-05 07:41 UTC, cstuder commented
Brought these names in-line with the Bootstrap ones: `sm, md, lg`.

2019-11-09 00:58 UTC, julians300 approved these changes

2019-11-09 00:58 UTC, julians300 commented
Looks great. Thanks!

2019-11-09 00:58 UTC, merged